name: dart_chromecast
version: 0.2.4
description: Cast videos to your ChromeCast device using Dart
homepage: https://github.com/terrabythia/dart_chromecast
publish_to: none

environment:
  sdk: '>=2.3.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  protobuf: '^2.0.0'
  protoc_plugin: ^20.0.0
  http: ^0.13.0
  args: ^2.0.0
  logging: ^1.0.0
  multicast_dns: ^0.2.2
  flutter:
    sdk: flutter
