name: dart_chromecast
version: 0.3.0
description: Cast videos to your ChromeCast device using Dart
homepage: https://github.com/terrabythia/dart_chromecast
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  protobuf: ^2.0.0
  protoc_plugin: ^20.0.0
  http: ^0.13.0
  multicast_dns:
    git:
      url: https://github.com/flutter/packages.git
      path: packages/multicast_dns
      ref: master
  flutter:
    sdk: flutter
