name: dart_chromecast
version: 0.3.0
description: Cast videos to your ChromeCast device using Dart
homepage: https://github.com/terrabythia/dart_chromecast
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  multicast_dns: ^0.3.2+7
  protobuf: ^3.1.0
  protoc_plugin: ^21.1.2
  rxdart: ^0.28.0

dev_dependencies:
  dart_rules:
    git:
      url: https://github.com/fastogt/dart_rules.git
      ref: main
